name: nckh
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  smooth_page_indicator: ^1.2.0+3
  socket_io_client: ^3.0.0
  syncfusion_flutter_charts: ^27.1.56
  flutter_svg: ^2.0.10+1
  timezone: ^0.9.4
  flutter_local_notifications: ^17.2.4
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  location: ^7.0.1
  google_maps_flutter: ^2.9.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/mainimg.jpg